# k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-project-deployment
  labels:
    app: car-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-project
  template:
    metadata:
      labels:
        app: car-project
    spec:
      containers:
        - name: car-project
          image: tungt149/car-project:latest
          ports:
            - containerPort: 8080
