# k8s/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: car-app-service
spec:
  type: LoadBalancer
  selector:
    app: car-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
