name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/car-project:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/car-project:latest

      - name: SSH to EC2 and run Docker
        run: |
          echo "${{ secrets.SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/car-project:latest
            docker stop car-app || true
            docker rm car-app || true
            docker run -d --name car-app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/car-project:latest
          EOF
